import java.lang.Math;
import java.util.*;
class RandException{
   public static void main(String args[])
   { int n;
       Scanner sc=new Scanner(System.in);
       System.out.println("enter the number 2 ");
       n=sc.nextInt();
       double rand = Math.random(); // generating random point
    System.out.println("Random Number: " + rand);
    System.out.println();
    System.out.println("when the random the point"+rand+ " is closer to the origin less than 2 cm exception is generated ");
    
  try{
      if(rand<=2)
       throw new RandumException();
       // throwing the exception manually
  }
 catch(RandumException e)
 {
    System.out.println(e.getMessage()) ;
 }
}
}
class RandumException extends Exception
{
   RandumException() 
   {
    System.out.println("\nRandumnumberexception");
    } 
RandumException(String message) 
   {
    super("\nRandumnumberexception");
    }
}
